### ISSUE TITLE
Various issues upgrading from 2.0 to 2.1 (master)

### ISSUE THREAD

**Issue by thiell** [phobos-storage/phobos#14]
When upgrading from 2.0 to current master branch:

DB upgrade OK:

```
[root@elm-ent-db01 ~]# phobos_db version
2.0
[root@elm-ent-db01 ~]# phobos_db migrate
You are about to upgrade database schema from version 2.0 to version 2.1.
Do you want to continue? [y/N]: y
[root@elm-ent-db01 ~]# phobos_db version
2.1
```

TLC cannot load:

```[root@elm-ent-dm01 ~]# systemctl status tlc
× tlc.service - Tape Library Controler (TLC) daemon
     Loaded: loaded (/usr/lib/systemd/system/tlc.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Wed 2024-09-11 09:01:34 PDT; 1h 29min ago
        CPU: 6ms

Sep 11 09:01:34 elm-ent-dm01 systemd[1]: Starting Tape Library Controler (TLC) daemon...
Sep 11 09:01:34 elm-ent-dm01 tlc[3150]: 2024-09-11 09:01:34.468706000 <ERROR> No default tape library defined in config: Invalid argument (22)
Sep 11 09:01:34 elm-ent-dm01 systemd[1]: tlc.service: Control process exited, code=exited, status=234/n/a
Sep 11 09:01:34 elm-ent-dm01 systemd[1]: tlc.service: Failed with result 'exit-code'.
Sep 11 09:01:34 elm-ent-dm01 systemd[1]: Failed to start Tape Library Controler (TLC) daemon.```
```

Here, the error messages are helpful, and the fix is to explicitly define these new configuration parameters in `phobos.conf`:
```
# default library
default_dir_library = legacy
default_rados_library = legacy
default_tape_library = legacy
```

Now, even with that change, `phobosd` also complains:

```
[root@elm-ent-dm01 ~]# systemctl status phobosd
● phobosd.service - Phobos Local Resource Scheduler (LRS) daemon
     Loaded: loaded (/usr/lib/systemd/system/phobosd.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/phobosd.service.d
             └─override.conf
     Active: active (running) since Wed 2024-09-11 10:39:37 PDT; 8min ago
    Process: 4962 ExecStart=/usr/sbin/phobosd (code=exited, status=0/SUCCESS)
   Main PID: 4963 (phobosd)
      Tasks: 3 (limit: 818930)
     Memory: 1.3M
        CPU: 49ms
     CGroup: /system.slice/phobosd.service
             └─4963 /usr/sbin/phobosd

Sep 11 10:39:37 elm-ent-dm01 systemd[1]: Starting Phobos Local Resource Scheduler (LRS) daemon...
Sep 11 10:39:37 elm-ent-dm01 phobosd[4963]: 2024-09-11 10:39:37.315810000 <ERROR> Request failed: syntax error at or near "FROM": Invalid argument (22)
Sep 11 10:39:37 elm-ent-dm01 phobosd[4963]: 2024-09-11 10:39:37.323564000 <ERROR> Request failed: syntax error at or near "FROM": Invalid argument (22)
Sep 11 10:39:37 elm-ent-dm01 systemd[1]: Started Phobos Local Resource Scheduler (LRS) daemon.
```

Same error here:
```
[root@elm-ent-dm01 ~]# phobos -v drive list
2024-09-11 10:44:13,452 <ERROR> Request failed: syntax error at or near "FROM": Invalid argument
Traceback (most recent call last):
  File "/usr/bin/phobos", line 30, in <module>
    phobos_main()
  File "/usr/lib64/python3.9/site-packages/phobos/cli.py", line 2605, in phobos_main
    pac.run()
  File "/usr/lib64/python3.9/site-packages/phobos/cli.py", line 2591, in run
    getattr(target_inst, 'exec_%s' % action.replace('-', '_'))()
  File "/usr/lib64/python3.9/site-packages/phobos/cli.py", line 2102, in exec_list
    objs = list(self.client.devices.get(family=self.family, **kwargs))
  File "/usr/lib64/python3.9/site-packages/phobos/core/dss.py", line 235, in get
    raise EnvironmentError(rc, "Cannot issue get request")
OSError: [Errno -22] Cannot issue get request
```

The rest seems to work:
```
[root@elm-ent-dm01 ~]# phobos tape list | wc -l
650
[root@elm-ent-dm01 ~]# phobos ping phobosd
2024-09-11 10:44:52,107 <INFO> Ping sent to phobosd successfully
[root@elm-ent-dm01 ~]# phobos ping tlc
2024-09-11 10:44:54,280 <INFO> Ping sent to TLC successfully
```

Any ideas?

**Comment by thiell** [comment]
Debug output from `phobos -s debug drive list`:
```
Sep 11 11:23:50 elm-ent-dm01 phobos[5503]: 2024-09-11 11:23:50,183 <DEBUG> [5503/pho_cfg_get_env:cfg.c:196] environment: PHOBOS_TAPE_MODEL_supported_list=<NULL>
Sep 11 11:23:50 elm-ent-dm01 phobos[5503]: 2024-09-11 11:23:50,183 <DEBUG> [5503/pho_cfg_get_local:cfg.c:242] config file: tape_model::supported_list=LTO5,LTO6,LTO7,LTO8,LTO9,T10KB,T10KC,T10KD
Sep 11 11:23:50 elm-ent-dm01 phobos[5503]: 2024-09-11 11:23:50,183 <DEBUG> [5503/pho_cfg_get_env:cfg.c:196] environment: PHOBOS_DSS_connect_string=<NULL>
Sep 11 11:23:50 elm-ent-dm01 phobos[5503]: 2024-09-11 11:23:50,183 <DEBUG> [5503/pho_cfg_get_local:cfg.c:242] config file: dss::connect_string=dbname=phobos host=10.4.0.132 user=phobos password=phobos
Sep 11 11:23:50 elm-ent-dm01 phobos[5503]: 2024-09-11 11:23:50,190 <DEBUG> [5503/execute:dss_utils.c:70] Executing request: 'SELECT * FROM schema_info WHERE version = '2.1';'
Sep 11 11:23:50 elm-ent-dm01 phobos[5503]: 2024-09-11 11:23:50,191 <DEBUG> [5503/dss_generic_get:dss.c:178] ENTERING dss_generic_get()
Sep 11 11:23:50 elm-ent-dm01 phobos[5503]: 2024-09-11 11:23:50,191 <DEBUG> [5503/dss_generic_get:dss.c:211] Executing request: 'SELECT family, model, device.id, library, adm_status,  host, path FROM device FROM device WHERE family = 'tape';'
Sep 11 11:23:50 elm-ent-dm01 phobos[5503]: 2024-09-11 11:23:50,191 <DEBUG> [5503/execute:dss_utils.c:70] Executing request: 'SELECT family, model, device.id, library, adm_status,  host, path FROM device FROM device WHERE family = 'tape';'
Sep 11 11:23:50 elm-ent-dm01 phobos[5503]: 2024-09-11 11:23:50,191 <ERROR> [5503/execute:dss_utils.c:74] Request failed: syntax error at or near "FROM": Invalid argument
```

Looks like a duplicate "FROM device". I will see if I can narrow this down.

**Comment by thiell** [comment]
This seems to fix it:
```diff
diff --git a/src/dss/device.c b/src/dss/device.c
index 3707294..8e3c710 100644
--- a/src/dss/device.c
+++ b/src/dss/device.c
@@ -129,8 +129,7 @@ static int device_select_query(GString **conditions, int n_conditions,
 {
     g_string_append(request,
                     "SELECT family, model, device.id, library, adm_status, "
-                    " host, path FROM device"
-                    " FROM device");
+                    " host, path FROM device");
 
     /* If we want to sort with a column from the "lock" table, we need to
      * retrieve the "lock" table because the information is not in the "device"
```

**Comment by valeriyoann** [comment]
Hello, the issue was with an invalid push on our side. Master should now be fixed, and this bug isn't present anymore.

Thanks for the help !
