### ISSUE TITLE
phobosd apparently stuck

### ISSUE THREAD

**Issue by thiell** [phobos-storage/phobos#17]
I hit some kind of deadlock (with the current master branch), where nothing is happening anymore. `lhsmtool_phobos` received some archive requests, but nothing happened on the phobosd side:

```Sep 18 00:37:23 elm-ent-dm04 sh[2489943]: 2024-09-18 00:37:23.090544000 <INFO> archiving '/elm/.lustre/fid/0x2c0000799:0x1a7f8:0x0'
Sep 18 00:37:23 elm-ent-dm04 sh[2489943]: 2024-09-18 00:37:23.091014000 <INFO> adding layout information key='layout', value='stripe_count=1,stripe_size=1048576,pattern=raid0'
Sep 18 00:37:23 elm-ent-dm04 sh[2489943]: 2024-09-18 00:37:23.091540000 <VERBOSE> hints provided hints='tag=mr,tag=p-srcc,tag=n3', len=24
Sep 18 00:37:23 elm-ent-dm04 sh[2489943]: 2024-09-18 00:37:23.091551000 <VERBOSE> hints #0  key='tag' val='mr'
Sep 18 00:37:23 elm-ent-dm04 sh[2489943]: 2024-09-18 00:37:23.091557000 <VERBOSE> adding tag 'mr'
Sep 18 00:37:23 elm-ent-dm04 sh[2489943]: 2024-09-18 00:37:23.091560000 <VERBOSE> hints #1  key='tag' val='p-srcc'
Sep 18 00:37:23 elm-ent-dm04 sh[2489943]: 2024-09-18 00:37:23.091563000 <VERBOSE> adding tag 'p-srcc'
Sep 18 00:37:23 elm-ent-dm04 sh[2489943]: 2024-09-18 00:37:23.091568000 <VERBOSE> hints #2  key='tag' val='n3'
Sep 18 00:37:23 elm-ent-dm04 sh[2489943]: 2024-09-18 00:37:23.091574000 <VERBOSE> adding tag ‘n3'
…
then nothing
```

No visible activity. Interestingly, phobosd was reporting ongoing io on all four drives.:
```
[root@elm-ent-dm04 ~]# phobos drive status
|   address | currently_dedicated_to   | device    | media    | mount_path       | name                            | ongoing_io   | serial     |
|-----------|--------------------------|-----------|----------|------------------|---------------------------------|--------------|------------|
|        12 | W                        | /dev/sg8  | 010037L9 | /mnt/phobos-sg8  | /dev/tape/by-id/scsi-10410057FB | True         | 10410057FB |
|        13 | W                        | /dev/sg18 | 010038L9 | /mnt/phobos-sg18 | /dev/tape/by-id/scsi-10420057FB | True         | 10420057FB |
|        14 | W                        | /dev/sg9  | 010024L9 | /mnt/phobos-sg9  | /dev/tape/by-id/scsi-10430057FB | True         | 10430057FB |
|        15 | W                        | /dev/sg19 | 010048L9 | /mnt/phobos-sg19 | /dev/tape/by-id/scsi-10440057FB | True         | 10440057FB |
```

phobosd gstack:

```bash
[root@elm-ent-dm04 ~]# gstack 2463516
Thread 8 (Thread 0x7f4a8cbb3640 (LWP 2468633) "phobosd"):
#0  0x00007f4a9049c39a in __futex_abstimed_wait_common () from /usr/lib64/libc.so.6
#1  0x00007f4a9049eea4 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib64/libc.so.6
#2  0x000055fa50f6725f in thread_signal_timed_wait ()
#3  0x000055fa50f5ab7b in lrs_dev_thread ()
#4  0x00007f4a9049f802 in start_thread () from /usr/lib64/libc.so.6
#5  0x00007f4a9043f450 in clone3 () from /usr/lib64/libc.so.6
Thread 7 (Thread 0x7f4a8d3b4640 (LWP 2468525) "phobosd"):
#0  0x00007f4a9049c39a in __futex_abstimed_wait_common () from /usr/lib64/libc.so.6
#1  0x00007f4a9049eea4 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib64/libc.so.6
#2  0x000055fa50f6725f in thread_signal_timed_wait ()
#3  0x000055fa50f5ab7b in lrs_dev_thread ()
#4  0x00007f4a9049f802 in start_thread () from /usr/lib64/libc.so.6
#5  0x00007f4a9043f450 in clone3 () from /usr/lib64/libc.so.6
Thread 6 (Thread 0x7f4a8dbb5640 (LWP 2468472) "phobosd"):
#0  0x00007f4a9049c39a in __futex_abstimed_wait_common () from /usr/lib64/libc.so.6
#1  0x00007f4a9049eea4 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib64/libc.so.6
#2  0x000055fa50f6725f in thread_signal_timed_wait ()
#3  0x000055fa50f5ab7b in lrs_dev_thread ()
#4  0x00007f4a9049f802 in start_thread () from /usr/lib64/libc.so.6
#5  0x00007f4a9043f450 in clone3 () from /usr/lib64/libc.so.6
Thread 5 (Thread 0x7f4a8e3cb640 (LWP 2464990) "gmain"):
#0  0x00007f4a9054291f in poll () from /usr/lib64/libc.so.6
#1  0x00007f4a9090a09c in g_main_context_iterate.constprop () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f4a908b25f3 in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f4a908b2641 in glib_worker_main () from /usr/lib64/libglib-2.0.so.0
#4  0x00007f4a908e35e2 in g_thread_proxy () from /usr/lib64/libglib-2.0.so.0
#5  0x00007f4a9049f802 in start_thread () from /usr/lib64/libc.so.6
#6  0x00007f4a9043f450 in clone3 () from /usr/lib64/libc.so.6
Thread 4 (Thread 0x7f4a8ebe0640 (LWP 2463519) "phobosd"):
#0  0x00007f4a9049c39a in __futex_abstimed_wait_common () from /usr/lib64/libc.so.6
#1  0x00007f4a9049eea4 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib64/libc.so.6
#2  0x000055fa50f6725f in thread_signal_timed_wait ()
#3  0x000055fa50f6928e in lrs_sched_thread.lto_priv ()
#4  0x00007f4a9049f802 in start_thread () from /usr/lib64/libc.so.6
#5  0x00007f4a9043f450 in clone3 () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7f4a8f3e1640 (LWP 2463518) "phobosd"):
#0  0x00007f4a9049c39a in __futex_abstimed_wait_common () from /usr/lib64/libc.so.6
#1  0x00007f4a9049eea4 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib64/libc.so.6
#2  0x000055fa50f6725f in thread_signal_timed_wait ()
#3  0x000055fa50f6928e in lrs_sched_thread.lto_priv ()
#4  0x00007f4a9049f802 in start_thread () from /usr/lib64/libc.so.6
#5  0x00007f4a9043f450 in clone3 () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7f4a8fc13640 (LWP 2463517) "phobosd"):
#0  0x00007f4a9049c39a in __futex_abstimed_wait_common () from /usr/lib64/libc.so.6
#1  0x00007f4a9049eea4 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib64/libc.so.6
#2  0x000055fa50f6725f in thread_signal_timed_wait ()
#3  0x000055fa50f5ab7b in lrs_dev_thread ()
#4  0x00007f4a9049f802 in start_thread () from /usr/lib64/libc.so.6
#5  0x00007f4a9043f450 in clone3 () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7f4a902328c0 (LWP 2463516) "phobosd"):
#0  0x00007f4a9054ea6e in epoll_wait () from /usr/lib64/libc.so.6
#1  0x000055fa50f52cdf in main ()
```

I occasionnally hit such situations where `phobosd` just seems to do nothing. Even stopping it is difficult. I often end up `ltfsck` all local drives after that.
Is there a way to list the current requests or clients and their status, to help troubleshoot? Something like `phobos requests list` :) Thanks!

**Comment by patlucas** [comment]
The phobosd scheduling was intensively rebuilt and is still under construction.
